### ISSUE TITLE
Come up with a better way to sync python api and the execution engine

### ISSUE THREAD

**Issue by shreyashankar** [ucbepic/docetl#107]
Currently, one has to manually update `schemas.py` and `api.py` to match operations and executors. I wonder if there's a way we can automatically generate the python API, or at least, do a sync and come up with a better plan to sync.

**Comment by redhog** [comment]
If you generate json-schema from the operation signatures (the parameter type annotations etc), you could generate the dataclasses you use for the python API on the fly from that.

However, I think it might be worth it to reevaluate what the python API should actually _do_. In my mind, it doesn't need those classes. It's fine to have dictionaries and lists (parsed yaml) be the input - the pipeline already does a syntax check.

However, what would be useful would be for the input and output to not be files, but be python variables.

E.g. an api like this:

```
p = docetl.Pipeline({
  "operarations": [...],
  "pipeline": {
    "steps": ["extract-stuff", "unnest-stuff", "resolve-stuff"]
  }
}) # This does the syntax check

output = p.run([
  {"text": "Some text..."}, {"text": "Another text..."}, ...
])
print(output)
```

**Comment by shreyashankar** [comment]
This makes a ton of sense

**Comment by redhog** [comment]
And for loading/saving, you'd add:

`datasets = p.load()`

and

`p.save(data)`

that would load/save according to the `dataset` and `output` sections (and throw an exception if they are not present, they'd have to be optional for the above API to work).

That would also mean that the main cli would just do

```
p = docetl.Pipeline(yaml.load(filename))
p.save(p.run(p.load()))
```

(Hm, this would mean `run()` takes a dictionary of `{datasetname: [items...]}`, not just `[items...]` as parameter. Not as obvious, but given that the pipeline can have multiple inputs I guess we have to)
