### ISSUE TITLE
Set .env config / LLM keys in the UI

### ISSUE THREAD

**Issue by shreyashankar** [ucbepic/docetl#151]
If we are to have a hosted version of the tool, users need to able to set their keys; and we can save encrypted versions of them in their browser's localStorage.

**Comment by CinderZhang** [comment]
Can Azure OpenAI be used?

**Comment by shreyashankar** [comment]
Yes--since we use litellm for pipeline execution; you will need to set the env vars listed [here](https://docs.litellm.ai/docs/providers/azure)

AZURE_API_KEY and AZURE_API_BASE and AZURE_API_VERSION
