### ISSUE TITLE
Web part uses crypto.randomUUID from Web Crypto API which is available only in secure context (HTTPS), or localhost

### ISSUE THREAD

**Issue by plpycoin** [ucbepic/docetl#153]
## Description

When uploading a YAML file from a non-[localhost](https://localhost/) or non-HTTPS environment, the following problem is encountered:

![image](https://github.com/user-attachments/assets/14821d07-c330-4bc7-9f13-411193636de3)

## Likely causes 

https://stackoverflow.com/questions/74911304/crypto-module-not-loading-randomuuid-when-viewing-a-local-network-ip-address

**Comment by staru09** [comment]
Can you elaborate more about your use case and this issue too?

**Comment by redhog** [comment]
This is a problem mostly during testing, when running things from localhost and you don't need https. Add the following somewhere early in the code as a polyfill to fix:


```javascript
try {
  crypto.randomUUID();
} catch (e) {
  crypto.randomUUID = () => {
    var chars = crypto.getRandomValues(new Uint8Array(31));
    return "10000000-1000-4000-8000-100000000000".replace(
      /[018]/g,
      (c, i) => ((c ^ chars[i]) & (15 >> (c / 4))).toString(16)
    );
  };
}

```

**Comment by shreyashankar** [comment]
interesting that makes sense for the crypto API. these are just used for operation ids; I think it's fine to use another library like uuid. will make a PR to fix
