### ISSUE TITLE
Unable to perform reduce operation on list

### ISSUE THREAD

**Issue by gcoolgithub** [ucbepic/docetl#159]
I am using the map operation  in the pipeline.yaml to generate the following o/p
{
"content": "abcde",
"classification": ["CLASS1"]
},
{
"content": "qwerty",
"classification": ["CLASS1","CLASS2"]
}

I used the reduce operation to aggregate the content based on the classification key (using reduce_key as "classification") in pipeline.yaml . However getting error 
"TypeError: unhashable type: 'list'"

**Comment by shreyashankar** [comment]
Thanks for flagging this! I just added support for list-type reduce_keys, which will sort the values in the list, convert to a tuple, and use this tuple for the reduce_key. LMK if this is not what you intended; feel free to re-open the issue.

**Comment by gcoolgithub** [comment]
The aggregation is working, but if the same classification is present in multiple lists, then it is getting aggregated separately.
example
If this is the input
{
            "content": "Document about AI and ML",
            "classifications": ["AI", "ML"]
        },
       {
            "content": "Document about AI only",
            "classifications": ["AI"]
        }

**then the expected aggregation  should be**
AI -> Document about AI and ML. Document about AI only
ML -> Document about AI and ML

**The actual aggregation is**
AI -> Document about AI only
AI,ML -> Document about AI and ML
