### ISSUE TITLE
Passing of max_tokens parameter to completion call

### ISSUE THREAD

**Issue by njbrake** [ucbepic/docetl#161]
Hi! I need to be able to pass a `max_tokens` parameter to the completion() function in this code:

https://github.com/ucbepic/docetl/blob/a58d7a70ac65a0d3f2615bcde9d1aa901e4dc575/docetl/operations/utils.py#L832-L855

The completion() function supports the max_token parameter so I assume its only a matter of adding support to map a configuration from the input yaml configuration into this function. Do you have any input about what should be done to support this feature? Thanks!

**Comment by shreyashankar** [comment]
good point--let me expose a `litellm_params` object that can be passed in from the client, so you can add things like `max_tokens`, `temperature`, etc.

**Comment by shreyashankar** [comment]
Just merged the PR; see the `litellm_completion_kwargs` here: https://ucbepic.github.io/docetl/concepts/operators/#common-attributes
