### ISSUE TITLE
The information of validating guardrails and gleaning cannot be saved.[Web-UI]

### ISSUE THREAD

**Issue by plpycoin** [ucbepic/docetl#164]
As stated in the title, the validating information cannot be saved and executed correctly through the web-ui.

**Comment by shreyashankar** [comment]
Thanks for flagging! I'll take a look later today

**Comment by shreyashankar** [comment]
Hope it works now; please let me know!

**Comment by plpycoin** [comment]
LGTM, Thanks!👍👍👍
