### ISSUE TITLE
AttributeError: 'Console' object has no attribute 'post_optimizer_status'

### ISSUE THREAD

**Issue by sarveshshh8** [ucbepic/docetl#172]
when i use this , pipeline = pipeline.optimize(model="gpt-4o-mini")
it gives me this error

**Comment by shreyashankar** [comment]
Ah this was a bug we fixed a week ago; any chance you need to rebase your fork?

**Comment by sarveshshh8** [comment]
thanks it works now

**Comment by shreyashankar** [comment]
Awesome; closing!
