### ISSUE TITLE
Execution of docetl on AWS lambda fails

### ISSUE THREAD

**Issue by yogitha2023** [ucbepic/docetl#180]
Error message:
`[ERROR] OSError: [Errno 30] Cache directory "/home/sbx_user1051/.docetl/llm_cache" does not exist and could not be created`

Deploying docetl to AWS lambda fails, because AWS lambda does not allow write to home directory. AWS lambda writes are only supported to the /tmp directory.

DOCETL_HOME_DIR is always created at users home directory, can this be configured through the env?

**Comment by shreyashankar** [comment]
Thanks for raising this! Does the PR you made fully address you issue? I'll close it if so :)

**Comment by yogitha2023** [comment]
Yes, the PR addresses it. You may close this.
