### ISSUE TITLE
Sample key only works for first step in pipeline when loading previous steps from cache

### ISSUE THREAD

**Issue by njbrake** [ucbepic/docetl#188]
Take this pipeline:

```
datasets:
  unprocessed:
    path: input.json
    type: file

default_model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0

pipeline:
  steps:
    - name: cool
      input: unprocessed
      operations:
        - cool_thing_1
        - cool_thing_2

  output:
    type: file
    path: result.json
    intermediate_dir: intermediate_results

operations:
   - name: cool_thing_1
    type: map
    output:
      schema:
        processed: str
    prompt: |
      Look at this thing:
      {{ input.unprocessed }}
      Do something

  - name: cool_thing_2
    type: map
    output:
      schema:
        processed: str
    # Note that this prompt is taking as input the output from the first operation
    prompt: |
      Look at this thing:
      {{ input.processed }}
      Do something

```

If you do `docetl run this_pipeline.yaml` and cancel the operation once cool_thing_2 starts, if you rerun the docetl command, everything loads from cache and all is well. 

However, lets say you want to just sample 10 outputs from that cool_thing_2 step so that you can verify that the output is doing what you want before you spend $$ to run the whole pipeline. If you add `sample: 10` to the `cool_thing_2` stage and run docetl, it starts processing but {{input.processed}} is an empty string!

I think this is some sort of issue with caching or sampling, where sampling later on in the pipeline no longer has the outputs from the previous operation available.

Let me know if this isn't clear.

**Comment by shreyashankar** [comment]
Thanks for opening this issue! I'll debug & push a fix over the weekend :-)
