### ISSUE TITLE
Integrate llama-index parsers

### ISSUE THREAD

**Issue by redhog** [ucbepic/docetl#51]
Wrap all llama-index parses to get easy access to a lot of file formats (pdfs, wikipedia etc)

**Comment by staru09** [comment]
1. As far as I know llama_index doesn't offer any other parser apart from [this](https://docs.llamaindex.ai/en/stable/llama_cloud/llama_parse/). 
Please correct me if I am wrong.

2. Not sure of other file types but for PDF [this](https://github.com/CosmosShadow/gptpdf) can be used. [Here](https://github.com/staru09/docetl/blob/main/docetl/gptpdf.py) is the sample code that converts a pdf file into a md file. 
I tested it with [this](https://arxiv.org/pdf/2310.10035) paper and here is the [output_file](https://github.com/user-attachments/files/17260355/output_final.md).

If you have any complex pdf file, do test it and lmk the results. If results are satisfactory I'll add a PR for this.

**Comment by redhog** [comment]
I'm thinking now with the plugin arch this could be done in a separate package "docetl-llama-index-parsers" or some such if it's too off topic for the main library.

**Comment by AntoineDao** [comment]
I am also starting to wonder whether a plugin system for file-readers might be a good idea. I appreciate this might be an early optimisation though... 🤔

**Comment by redhog** [comment]
@AntoineDao  So, I already built a plugin system, and the PR above could easily be moved to a separate repo.

However, the API for parsers is a bit limited, see https://github.com/ucbepic/docetl/issues/72, and it would be good to address that first...

I think parsing and loaders is where there is a near infinite set of libraries that could be useful to integrate with, and doing so directly in this repo would end up very messy. Hence plugins :)

**Comment by shreyashankar** [comment]
I agree that we'll eventually want a plugin system, but it currently feels a bit premature to do so...

If anyone has a concrete use case, please react and/or comment here. We can bump up the priority for this

**Comment by redhog** [comment]
Well, the entrypoint stuff I wrote /is/ a simple plugin system... I think that's good enough for now.
