### ISSUE TITLE
Outliers-filter

### ISSUE THREAD

**Issue by redhog** [ucbepic/docetl#58]
* Embed some field
* Calculate the average embedding across all entries
* Remove entries whose embeddings are farthest from the average
  * Remove the N farthest away
  * Remove the M farthest away percentiles
  * Remove those more than X standard deviations away

**Comment by ahmedtadde** [comment]
hey @redhog, this is an interesting proposal. Do you have 1-2 concrete cases where this would be useful?

**Comment by redhog** [comment]
I have one use case right now: Ingest a bunch of books or papers on a subject, extract all concepts and how they relate to each other. Unfortunately, cited authors and works end up being added as concepts! But I'm sure their embeddings would be quite far from the rest of the concepts...
