### ISSUE TITLE
Support UDFs

### ISSUE THREAD

**Issue by shreyashankar** [ucbepic/docetl#6]
Not all operations need to be LLM operations :-)

Users should be able to define Python functions for map and reduce operations, instead of LLM calls.

This will also enable a code synthesis optimization: if an operation can be accurately executed via code than an LLM call that operates directly on the document, then we should prefer the code implementation.

**Comment by staru09** [comment]
Is this available to work?

**Comment by shreyashankar** [comment]
yes!! feel free to take it! we might want a proposal first though, lmk what you think
