### ISSUE TITLE
Suggestion: A new sampler operation for debugging

### ISSUE THREAD

**Issue by redhog** [ucbepic/docetl#83]
An operation that samples a subset of the items, to be used when developing a pipeline. You stick it right before any part of the pipeline that you are developing on right now, making running that much cheaper while you try it out by only running it on a subset of the data.

Note: The random seed used for the sampling must be possible to set so that which items the subsequent operations work on stays the same even when you rerun the pipeline.

**Comment by shreyashankar** [comment]
Currently we allow operations to take in a `sample` parameter (just added to the docs in #87 )

**Comment by redhog** [comment]
Hm, I guess that solves the problem, but is less explicit to the user, and requires code in all operations...

**Comment by shreyashankar** [comment]
Hm why might someone add the sample param to each operator? If you sample the first operator, then there are fewer docs going into successive operators

**Comment by redhog** [comment]
Because you (or at least me) build a pipeline iteratively. I'd read in the full dataset, sample some and write the first map. If that works, I'd move the sampling and put it after the map, running it and checking the full intermediate map output. Then repeat for each stage until the whole pipeline is built... That way, you can at any point change your sampling to a wider selection, without having to rerun the whole pipeline, and once you're done with the last stage, you have the whole output for your original input.

**Comment by redhog** [comment]
Hm, that'd be interesting yes. I'll see if I can hack something together.
